config/routes.rb
Rails.application.routes.draw do

  get 'reports/new'
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'public/sessions#destroy'
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
    post '/users/guest_sign_out' => 'public/sessions#guest_sign_out'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/genre/search' => 'searches#genre_search'
  get '/search' => 'searches#search'

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      patch :cancel
    end
  end

  resources :games, except: [:show] do
    resource :play_games, only: [:create, :destroy]
    resources :reviews do
      resource :usefuls, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :notifications, only: [:index, :destroy]

	resources :reports, only: [:new, :create, :index, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable

	# バリデーション
	validates :nickname, presence: true,  uniqueness: true
	validates :email, presence: true, format: { with: /\A[a-zA-Z0-9]{1,}[@][a-zA-Z0-9]{1,}[.][a-zA-Z0-9]{1,}\z/ }, uniqueness: true
	validates :password, length: { minimum: 6, maximum: 20 }, on: :create

	# アソシエーション
	has_many :reviews, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :play_games, dependent: :destroy
	has_many :usefuls, dependent: :destroy
	has_many :notifications, dependent: :destroy
	has_many :reports, foreign_key: "reported_id", as: :content, dependent: :destroy

	has_one_attached :profile_image

	# 通報
	has_many :reporter, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
	has_many :reported, class_name: "Report", foreign_key: "reported_id", dependent: :destroy

	# ゲストアカウントを探し、無ければ作成
	def self.guest
		find_or_create_by!(email: 'guest@guest.com') do |user|
			user.password = SecureRandom.alphanumeric(10)
			user.nickname = 'ゲスト'
			# user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
		end
	end

	# ProfileImage設定なければデフォルトを表示
	def get_profile_image
		unless profile_image.attached?
			file_path = Rails.root.join('app/assets/images/no_profile_image.jpg')
			profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
		end
			profile_image
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_or_admin?
  before_action :ensure_correct_user, only: [:edit, :update]


  def show
    @user = User.find(params[:id])
    @reviews = Review.where(user_id: @user.id).order(useful_count: :desc).page(params[:page]).per(5)
    @comments = Comment.where(user_id: @user.id).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def cancel
    @user = current_user
    if @user.update(is_active: false)
      reset_session
      redirect_to root_path
    else
      render :show
    end
  end


  private

  # 本人かadminのみ
  def ensure_correct_user
    @user = User.find(params[:id])
    ## 違う場合はそのuserのProfileへ
    unless @user == current_user or admin_signed_in?
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :introduction, :is_active, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<table class=" table border border-dark", style="width:80%;">
	<th class="text-center align-middle border-bottom border-dark">
		Information
	</th>
	<% if user.is_active == false %>
		<tr>
			<td>Withdrawal User</td>
		</tr>
	<% end %>
	<tr>
		<td class="text-center align-middle">
			<% if user != current_user&& current_user.present? && current_user.nickname != 'ゲスト' %>
				<div class="report-btn text-right mr-2" id="report-btn-<%= user.id %>">
					<%= render "reports/report_btn", comment: user, content_id: user.id, content_type: user.class.name %>
				</div>
			<% end %>
			<%= image_tag user.get_profile_image, size: '100x100', alt: 'User Image' %>
		</td>
	</tr>
	<tr>
		<td class="align-middle">
			<p>Nickname</p>
			<div class="text-center"><%= user.nickname %></div>
		</td>
	</tr>
	<tr>
		<td class="align-middle">
			<p>Introduction</p>
			<div class="text-center"><%= user.introduction %></div>
		</td>
	</tr>
	<% if user == current_user or admin_signed_in? %>
		<% if user.nickname != 'ゲスト' %>
			<tr>
				<td class="text-center align-middle">
					<div><%= link_to 'Edit', edit_user_path(params[:id]), class: 'text-dark' %></div>
				</td>
			</tr>
		<% end %>
	<% end %>
</table>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<p class="font-weight-bold bg-secondary bg-secondary text-light mx-auto mt-5 p-1 h5">
			User Information Editing
		</p>
	</div>

	<div class="row">
		<div class="col-6 mx-auto">
			<%= render 'layouts/errors', obj: @user %>

			<%= form_with model: @user do |f| %>
				<div class="form-group text-nowrap mt-3 mb-3">
					<%= f.label :profile_image, 'Profile Image' %></br>
					<%= f.file_field :profile_image, accept: 'image/*', class: "ml-4" %>
					<small class="form-text text-muted ml-4">
						It's OK without this.
					</small>
				</div>

				<div class="form-group text-nowrap mt-3 mb-3">
					<%= f.label :nickname, 'Nickname' %></br>
					<%= f.text_field :nickname, class: "ml-4" %>
				</div>

				<div class="form-group text-nowrap mt-3 mb-3">
					<%= f.label :introduction, 'Introduction' %></br>
					<%= f.text_area :introduction, rows: '3', cols: '30', placeholder: 'Type your introduction here', class: "ml-4" %>
					<small class="form-text text-muted ml-4">
						It's OK without this.
					</small>
				</div>

				<% if admin_signed_in? %>
					<div class="form-group text-nowrap mt-3 mb-3">
						<%= f.label :is_active, "User Status" %>
						<div class="form-inline">
							<%= f.radio_button :is_active, :true, checked: @user.is_active, class: "ml-4 form-control" %>
							<%= label_tag 'is_active_true', 'Active', class: "ml-1" %>
							<%= f.radio_button :is_active, :false, checked: !@user.is_active, class: "ml-4 form-control" %>
							<%= label_tag 'is_active_false', 'Deleted', class: "ml-1" %>
						</div>
					</div>
				<% end %>

				<div class="form-group text-center">
					<%= f.submit 'Update', class: 'btn btn-secondary' %>
				</div>
			<% end %>

			<% if @user == current_user %>
				<div class="text-center">
					<%= button_to 'Delete', cancel_user_path(@user), method: :patch,
						data: { confirm: 'Are you sure you want to delete an account ?' }, class: "btn btn-dark" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class='container'>
	<% if @user.nickname != 'ゲスト' %>
		<div class='row'>
			<div class='col-6 col-md-3 mt-5'>
				<div>
					<%= render 'info', user: @user %>
				</div>
			</div>

			<div class='col-md-9 mt-5'>
				<span class="h2 mr-2">Reviews List</span><span>(<%= @user.reviews.count %>)</span>
				<% if @reviews.present? %>
					<% @reviews.each do |review| %>
						<div class="card my-2">
							<div class="row g-0">
								<div class="col-3">
									<div class="m-2 text-center">
										<%= link_to game_reviews_path(review.game) do %>
											<%= image_tag review.game.get_image, class: "obj-img", alt: 'Game Image' %>
										<% end %>
									</div>
								</div>
								<div class="col-9">
									<div class="d-flex justify-content-between mt-3 mb-2">
										<div class="">
											Game Name : <%= link_to review.game.name, game_reviews_path(review.game), class: 'text-dark' %>
										</div>
										<div class="mr-3">
											<small class="text-secondary"><%= review.created_at.strftime('%m/%d/%Y %H:%M') %></small>
										</div>
									</div>

									<div class="d-flex align-items-center">
										<div class="mr-3">
											Useful : <%= review.usefuls.count %>
										</div>
										<div class="ml-3">
											Comments : <%= review.comments.count %>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col">
									<div class="card-body border-top mx-2">
										<div class="card-text">
											<%= link_to safe_join(review.content.split("\n"),tag(:br)), game_review_path(review.game, review), class: 'text-dark' %>
										</div>
									</div>
								</div>
							</div>
						</div>
					<% end %>

					<div class="d-flex justify-content-center">
						<p>
							<%= paginate @reviews, theme: 'bootstrap-5' %>
						</p>
					</div>

				<% else %>
					<div class="m-3">
						Nothing
					</div>
				<% end %>


				<div class="mt-3">
					<span class="h2 mr-2">Comments List</span><span>(<%= @user.comments.count %>)</span>
					<% if @comments.present? %>
						<% @comments.each do |comment| %>
							<div class="card my-2">
								<div class="row g-0">
									<div class="col-3">
										<div class="m-2">
											<div class="text-center">
												<%= link_to game_reviews_path(comment.review.game) do %>
													<%= image_tag comment.review.game.get_image, class: "obj-img", alt: 'Game Image' %>
												<% end %>
											</div>

											<div class="ml-2">
												Game Name :
												<div class="text-center">
													<%= link_to comment.review.game.name, game_reviews_path(comment.review.game), class: 'text-dark' %>
												</div>
											</div>
										</div>
									</div>

									<div class="col-9">
										<div class="d-flex justify-content-between my-2">
											<h6 class="mt-2">Review</h6>
											<div class="mr-3">
												<small class="text-secondary"><%= comment.review.created_at.strftime('%m/%d/%Y %H:%M') %></small>
											</div>
										</div>

										<div>
											<%= link_to safe_join(comment.review.content.split("\n"),tag(:br)), game_review_path(comment.review.game, comment.review), class: 'text-dark' %>
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col">
										<div class="card-body border-top mx-2">
											<div class="d-flex justify-content-between">
												<div class="card-text">
													<%= link_to safe_join(comment.content.split("\n"),tag(:br)), game_review_path(comment.review.game, comment.review), class: 'text-dark' %>
												</div>
												<div class="">
													<small class="text-secondary"><%= comment.created_at.strftime('%m/%d/%Y %H:%M') %></small>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						<% end %>
					<% else %>
						<div class="m-3">
							Nothing
						</div>
					<% end %>
				</div>
			</div>
		</div>
	<% else %>
		<div class="text-center mt-4 mb-2">
			Sign up
			<%= link_to "here", users_guest_sign_out_path, method: :post %>
		</div>
		<p class="text-center mt-5 mb-5 h2">
			お試しいただき</br>
			ありがとうございます
		</p>
		<p class="text-center h5">
			ゲストは閲覧のみになります。</br>
			ゲームを追加したりレビューやコメントで</br>
			一緒にこのサイトを盛り上げていただけたら、</br>
			とても嬉しいです。</br>
			上記からサインアップお願いします！
		</p>
	<% end %>
</div>