config/routes.rb
Rails.application.routes.draw do

  get 'reports/new'
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'public/sessions#destroy'
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
    post '/users/guest_sign_out' => 'public/sessions#guest_sign_out'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/genre/search' => 'searches#genre_search'
  get '/search' => 'searches#search'

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      patch :cancel
    end
  end

  resources :games, except: [:show] do
    resource :play_games, only: [:create, :destroy]
    resources :reviews do
      resource :usefuls, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :notifications, only: [:index, :destroy]

	resources :reports, only: [:new, :create, :index, :destroy]

end

app/models/game.rb
class Game < ApplicationRecord

	# バリデーション
  validates :name, presence: true,  uniqueness: true
  validates :release_date, presence: true

  # アソシエーション
  has_many :reviews, dependent: :destroy
  belongs_to :genre
  has_many :play_games, dependent: :destroy

  has_one_attached :image

  # 並び替えを定義
  scope :latest, -> { order(release_date: :desc) }
  scope :earliest, -> { order(release_date: :asc) }
  scope :popular, -> { order(played_count: :desc) }

  # キーワード検索
  def self.search(keyword)
    where("facility_name LIKE ?", "%#{keyword}%")
  end

  # playedかどうかの確認
  def played_by?(user)
    play_games.exists?(user_id: user.id)
  end

  # GameImage無ければデフォルトを表示
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.png', content_type: 'image/png')
    end
      image
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :user_or_admin?
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    # 並び替え方法で分岐
    ## latestで新しい順
    if params[:latest] == "true"
      @games = Game.latest.page(params[:page]).per(12)
    ## earliestで古い順
    elsif params[:earliest] == "true"
      @games = Game.earliest.page(params[:page]).per(12)
    ## popularで人気順
    elsif params[:popular] == "true"
      @games = Game.popular.page(params[:page]).per(12)
    else
      @games = Game.all.page(params[:page]).per(12)
    end

    @genres = Genre.all
  end

  # GET /games/new
  def new
    @game = Game.new
    @genres = Genre.all
  end

  # GET /games/1/edit
  def edit
    @genres = Genre.all
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    if @game.save
      flash[:notice] = 'Success !'
      redirect_to game_reviews_path(@game)
    else
      @genres = Genre.all
      render 'new'
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    if @game.update(game_params)
      redirect_to game_reviews_path(@game)
    else
      @genres = Genre.all
      render 'edit'
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    redirect_to games_path
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :release_date, :genre_id, :image)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with model: game do |f| %>
	<div class="form-group text-nowrap mt-3 mb-3">
		<%= f.label :image, 'Game Image' %></br>
		<%= f.file_field :image, accept: "image/*", class: "ml-4" %>
		<small class="form-text text-muted ml-4">
			It's OK without this.
		</small>
	</div>
	<div class="form-group text-nowrap mt-3 mb-3">
		<%= f.label :name, 'Game Name' %></br>
		<%= f.text_field :name, class: "form-control ml-4" %>
		<small class="form-text text-muted ml-4">
			Please give a game name that everyone can understand.
		</small>
	</div>

	<div class="form-group text-nowrap mt-3 mb-3">
		<%= f.label :genre_id, 'Genre' %></br>
		<div class="ml-4">
			<%= f.select :genre_id, options_for_select(@genres.map { |g| [g.name, g.id] }, game.genre_id), {class: "form-control"} %>
		</div>
	</div>

	<div class="form-group text-nowrap mt-3 mb-3">
		<%= f.label :release_date, 'Release Date' %></br>
		<div class="ml-4">
			<%= raw sprintf(f.date_select(:release_date, start_year: 1975, end_year: Time.now.year, order: [:month, :day, :year], use_month_numbers: true, date_separator: '/')) %>
		</div>
	</div>

	<div class="text-center p-1">
		<%= f.submit %>
	</div>
<% end %>

app/views/games/_index.html.erb
<% if games.present? %>
	<div class="row">
		<% games.each do |game| %>
			<div class="col-6 col-md-4">
				<div class="card mb-3"
					data-controller="href"
					data-action="click->href#toHref"
					data-href="<%= game_reviews_path(game) %>"
					style="cursor: pointer;">

					<%= image_tag game.get_image, class: "card-img-top", alt: 'game image' %>

					<div class="card-body">
						<h5 class="card-title">
							<%= game.name %>
						</h5>
					</div>

					<ul class="list-group list-group-flush">
						<li class="list-group-item">
							Release Date : <%= game.release_date.strftime('%m/%d/%Y') %>
						</li>
						<li class="list-group-item">
							Played : <%= game.play_games.count %>
						</li>
						<li class="list-group-item">
							Reviews : <%= game.reviews.count %>
						</li>
					</ul>
				</div>
			</div>
		<% end %>
	</div>

<% else %>
	<div class="text-center">
		Nothing
	</div>
<% end %>

app/views/games/_info.html.erb
<table class="table border border-dark">
	<th class="text-center align-middle border-bottom border-dark">
		Information
	</th>
	<tr>
		<td class="align-middle">
			<div class="text-center">
				<%= image_tag game.get_image, class: "obj-img", alt: 'game image' %>
			</div>
		</td>
	</tr>
	<tr>
		<td class="align-middle">
			<p>Game name:</p>
			<div class="text-center">
				<%= game.name %>
			</div>
		</td>
	</tr>
	<tr>
		<td class="align-middle">
			<p>Genre:</p>
			<div class="text-center">
				<%= game.genre.name %>
			</div>
		</td>
	</tr>
	<tr>
		<td class="align-middle">
			<p>Release date:</p>
			<div class="text-center">
				<%= game.release_date.strftime('%m/%d/%Y') %>
			</div>
		</td>
	</tr>
	<tr>
		<td class="align-middle">
			<p>Played:</p>
			<div class="text-center", id="play_game_buttons_<%= game.id %>">
				<%= render 'play_games/btn', game: game %>
			</div>
		</td>
	</tr>
	<% if user_signed_in? %>
		<% if current_user.nickname != 'ゲスト' %>
			<tr>
				<td class="text-center">
					<%= link_to 'Edit', edit_game_path(game), class: 'text-dark' %>
				</td>
			</tr>
		<% end %>
	<% elsif admin_signed_in? %>
		<tr>
			<td class="text-center">
				<%= link_to 'Edit', edit_game_path(game), class: 'text-dark' %>
			</td>
		</tr>
	<% end %>
</table>

app/views/games/edit.html.erb
<div class="container">
	<div class="row">
		<p class="font-weight-bold bg-secondary bg-secondary text-light mx-auto mt-5 p-1 h5">
			Game Information Editing
		</p>
	</div>

	<div class="row">
		<div class="col-6 mx-auto">
			<%= render 'layouts/errors', obj: @game %>
			<%= render 'form', game: @game %>
			<div class="mt-3 text-center">
				<% if admin_signed_in? %>
					<%= button_to 'Delete', game_path(@game), method: :delete,
						data: { confirm: 'Are you sure you want to delete this game ?' }, class: "btn btn-dark my-2" %>
				<% end %>
				<%= link_to '< Reviews List >', game_reviews_path(@game), class: 'text-dark' %>
			</div>
		</div>
	</div>
</div>

app/views/games/index.html.erb
<div class='container'>
	<% if user_signed_in? %>
		<% if current_user.nickname == 'ゲスト' %>
			<div class="text-center mt-4 mb-2">
				Sign up
				<%= link_to "here", users_guest_sign_out_path, method: :post %>
			</div>
		<% end %>
	<% end %>
	<div class='row'>
		<div class='col-6 col-md-3 mt-5'>
			<div>
				<%= render 'layouts/genre', genres: @genres %>
			</div>
		</div>

		<div class='col-md-9 mt-5'>
			<div class="my-3">
				<span class="h2 mr-2">Games List</span> <span>(<%= Game.all.count %>)</span>
				<div class="ml-2">
					<% if user_signed_in? %>
						<% if current_user.nickname != 'ゲスト' %>
							<%= link_to 'Add Game', new_game_path, class: 'text-dark' %>
						<% end %>
					<% elsif admin_signed_in? %>
						<%= link_to 'Add Game', new_game_path, class: 'text-dark' %>
					<% end %>
				</div>
			</div>
			<div class="mb-2">
				<%= link_to 'New', games_path(latest: "true"), class: 'text-dark' %> |
				<%= link_to 'Old', games_path(earliest: "true"), class: 'text-dark' %> |
				<%= link_to 'Popular', games_path(popular: "true"), class: 'text-dark' %>
			</div>
			<%= render 'index', games: @games %>

			<div class="d-flex justify-content-center">
				<p>
					<%= paginate @games, theme: 'bootstrap-5' %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/games/new.html.erb
<div class="container">
	<div class="row">

		<p class="font-weight-bold bg-secondary bg-secondary text-light mx-auto my-5 p-1 h5">
			New Game
		</p>
	</div>

	<div class="row">
		<div class="col-6 mx-auto">
			<%= render 'layouts/errors', obj: @game %>
			<%= render 'form', game: @game %>
			<div class="mt-3 text-center">
				<%= link_to '< Games List >', games_path, class: 'text-dark' %>
			</div>
		</div>
	</div>
</div>