config/routes.rb
Rails.application.routes.draw do

  get 'reports/new'
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'public/sessions#destroy'
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
    post '/users/guest_sign_out' => 'public/sessions#guest_sign_out'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/genre/search' => 'searches#genre_search'
  get '/search' => 'searches#search'

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      patch :cancel
    end
  end

  resources :games, except: [:show] do
    resource :play_games, only: [:create, :destroy]
    resources :reviews do
      resource :usefuls, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :notifications, only: [:index, :destroy]

	resources :reports, only: [:new, :create, :index, :destroy]

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	before_action :user_or_admin?

	def genre_search
		@genres = Genre.all
		genre_id = params[:genre_id]
		@genre = Genre.find(genre_id)
		games = Game.where(genre_id: genre_id)
		@genre_games = games.all
		# 並び替え方法で分岐
		## latestで新しい順
		if params[:latest] == "true"
			@games = games.latest.page(params[:page]).per(12)
		## earliestで古い順
		elsif params[:earliest] == "true"
			@games = games.earliest.page(params[:page]).per(12)
		## popularで人気順
		elsif params[:popular] == "true"
			@games = games.popular.page(params[:page]).per(12)
		else
			@games = games.all.page(params[:page]).per(12)
		end
	end

	def search
		games = Game.where('name LIKE ?', "%#{params[:content]}%")
		@search_games = games.all
		# 並び替え方法で分岐
		## latestで新しい順
		if params[:latest] == "true"
			@games = games.latest.page(params[:page]).per(12)
		## earliestで古い順
		elsif params[:earliest] == "true"
			@games = games.earliest.page(params[:page]).per(12)
		## popularで人気順
		elsif params[:popular] == "true"
			@games = games.popular.page(params[:page]).per(12)
		else
			@games = games.all.page(params[:page]).per(12)
		end
		@genres = Genre.all
	end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/genre_search.html.erb
<div class='container'>
	<% if user_signed_in? %>
		<% if current_user.nickname == 'ゲスト' %>
			<div class="text-center mt-4 mb-2">
				Sign up
				<%= link_to "here", users_guest_sign_out_path, method: :post %>
			</div>
		<% end %>
	<% end %>
	<div class='row'>
		<div class='col-6 col-md-3 mt-5'>
			<div>
				<%= render 'layouts/genre', genres: @genres %>
			</div>
		</div>

		<div class='col-md-9 mt-5'>
			<div class="my-3">
				<span class="h2 mr-2">「<%= @genre.name %>」Games List</span> <span>(<%= @genre_games.count %>)</span>
				<div class="ml-2">
					<% if user_signed_in? %>
						<% if current_user.nickname != 'ゲスト' %>
							<%= link_to 'Add Game', new_game_path, class: 'text-dark' %>
						<% end %>
					<% elsif admin_signed_in? %>
						<%= link_to 'Add Game', new_game_path, class: 'text-dark' %>
					<% end %>
				</div>
			</div>
			<div class="mb-2">
				<%= link_to 'New', genre_search_path(genre_id: @genre.id, latest: "true"), class: 'text-dark' %> |
				<%= link_to 'Old', genre_search_path(genre_id: @genre.id, earliest: "true"), class: 'text-dark' %> |
				<%= link_to 'Popular', genre_search_path(genre_id: @genre.id, popular: "true"), class: 'text-dark' %>
			</div>
			<%= render 'games/index', games: @games %>

			<div class="d-flex justify-content-center">
				<p>
					<%= paginate @games, theme: 'bootstrap-5' %>
				</p>
			</div>

		</div>
	</div>
</div>

app/views/searches/search.html.erb
<div class='container'>
	<% if user_signed_in? %>
		<% if current_user.nickname == 'ゲスト' %>
			<div class="text-center mt-4 mb-2">
				Sign up
				<%= link_to "here", users_guest_sign_out_path, method: :post %>
			</div>
		<% end %>
	<% end %>
	<div class='row'>
		<div class='col-6 col-md-3 mt-5'>
			<div>
				<%= render 'layouts/genre', genres: @genres %>
			</div>
		</div>

		<div class='col-md-9 mt-5'>
			<% if @games.empty? %>
				<p class="font-weight-bold d-flex justify-content-center">「<%= params[:content] %>」で検索したゲームは見つかりませんでした。</p>
			<% else %>
				<div class="my-3">
					<span class="h2 mr-2">「<%= params[:content] %>」Search List</span> <span>(<%= @search_games.count %>)</span>
					<div class="ml-2">
						<% if user_signed_in? %>
							<% if current_user.nickname != 'ゲスト' %>
								<%= link_to 'Add Game', new_game_path, class: 'text-dark' %>
							<% end %>
						<% elsif admin_signed_in? %>
							<%= link_to 'Add Game', new_game_path, class: 'text-dark' %>
						<% end %>
					</div>
				</div>
				<div class="mb-2">
					<%= link_to 'New', search_path(content: params[:content], latest: "true"), class: 'text-dark' %> |
					<%= link_to 'Old', search_path(content: params[:content], earliest: "true"), class: 'text-dark' %> |
					<%= link_to 'Popular', search_path(content: params[:content], popular: "true"), class: 'text-dark' %>
				</div>
				<%= render 'games/index', games: @games %>

				<div class="d-flex justify-content-center">
					<p>
						<%= paginate @games, theme: 'bootstrap-5' %>
					</p>
				</div>
			<% end %>
		</div>
	</div>
</div>