config/routes.rb
Rails.application.routes.draw do

  get 'reports/new'
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'public/sessions#destroy'
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
    post '/users/guest_sign_out' => 'public/sessions#guest_sign_out'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/genre/search' => 'searches#genre_search'
  get '/search' => 'searches#search'

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      patch :cancel
    end
  end

  resources :games, except: [:show] do
    resource :play_games, only: [:create, :destroy]
    resources :reviews do
      resource :usefuls, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :notifications, only: [:index, :destroy]

	resources :reports, only: [:new, :create, :index, :destroy]

end

app/models/report.rb
class Report < ApplicationRecord
	# 通報者を示す関連付け
	belongs_to :reporter, class_name: "User", foreign_key: "reporter_id"

	# 通報対象を示す関連付け
	belongs_to :reported, class_name: "User", foreign_key: "reported_id"

	# 通報対象のコンテンツを示す多様性（Polymorphic）関連付け
	belongs_to :content, polymorphic: true

	# 通報理由
	enum reason: {
		malicious_expression: 0,      # 悪意のある表現
		inappropriate_content: 1,     # 不適切なコンテンツ
		misinformation: 2,            # 誤った情報
		commercial_purposes: 3,       # 商業目的
		spam: 4,                      # スパム
		other: 5                      # その他
	}

	def link_to_reported_user(report)
	  if report.reported.is_a?(User)
	    link_to report.reported.nickname, user_path(report.reported), target: "_blank"
	  elsif report.reported.is_a?(Review)
	    link_to "View Review", review_path(report.reported), target: "_blank"
	  elsif report.reported.is_a?(Comment)
	    link_to "View Comment", comment_path(report.reported), target: "_blank"
	  else
	    "Unknown Type"
	  end
	end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_admin!, only: [:index, :destroy]
	def new
		@report = Report.new
		render :layout => false
	end

	def index
		@reports = Report.all.order(created_at: :desc).page(params[:page]).per(10)

		@reports.where(is_checked: false).each do |report|
      report.update(is_checked: true)
    end
	end

	def create
		# ユーザーが報告する対象の種類とIDを取得
		content_type = params[:report][:content_type]
		content_id = params[:report][:content_id]

		# 対象のコンテンツをデータベースから取得
		@content = content_type.constantize.find(content_id)

		# 対象のコンテンツが存在する場合
		if @content
			# 新しい報告オブジェクトを作成
			@report = Report.new(report_params)

			# 報告者と報告対象を設定
			@report.reporter = current_user
			if @content.is_a?(User)
			  @report.reported = @content
			else
				@report.reported = @content.user
			end

			# 報告をデータベースに保存
			if @report.save
				respond_to do |format|
					format.js { render "create_success" } # 成功時のレスポンス
				end
			else
				respond_to do |format|
					format.js { render "create_failure" } # 失敗時のレスポンス
				end
			end
		end

	rescue ActiveRecord::NotNullViolation => e
		# NOT NULL 制約違反が発生した場合もエラー処理
		respond_to do |format|
			format.js { render "create_failure", status: :unprocessable_entity } # エラーレスポンスを返す
		end
	end

	def destroy
		@report = Report.find(params[:id]).destroy
		redirect_to request.referer
	end

	private

	# コンテンツをデータベースから取得するメソッド
	def find_content(content_type, content_id)
		content_class = content_type.classify.constantize
		content_class.find_by(id: content_id)
	end

	def report_params
		params.require(:report).permit(:content_type, :content_id, :reason)
	end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_report_btn.html.erb
 <!-- モーダルウィンドウのトリガーボタンを追加 -->
<i class="fas fa-ellipsis open-report-modal-button" data-comment-id="<%= comment.id %>"
	data-content-id="<%= comment.id %>" data-content-type="<%= comment.class.name %>" data-report-success="true"
	style="cursor: pointer;"></i>

<div id="report-modal" class="modal">
	<div class="common-modal-content"></div>
</div>

<script>
	$(document).ready(function() {
		// モーダルウィンドウを開くボタンがクリックされたときの処理
		$('.open-report-modal-button').click(function() {
			const contentId = $(this).data("content-id");
			const contentType = $(this).data("content-type");

			// Ajaxリクエストを送信して報告フォームを取得
			$.ajax({
				url: '<%= new_report_path %>',
				type: 'GET',
				data: { content_id: contentId, content_type: contentType },
				success: function(response) {
					// 取得した報告フォームをモーダル内に表示
					$('#report-modal .common-modal-content').html(response);
					$('#report-modal').addClass('fade-in').show();
				}
			});
		});

		// モーダルウィンドウの背景部分がクリックされたときの処理
		$('#report-modal').on('click', function(event) {
			if (event.target === this) {
				// モーダルを非表示にするアニメーション
				$(this).addClass('fade-out');
				setTimeout(() => {
					$(this).hide().removeClass('fade-out');
				}, 300);
			}
		});
	});
</script>

app/views/reports/_report_form.html.erb
<%= simple_form_for report, remote: true do |f| %>
	<div class="form-check">
		<%= f.radio_button :reason, "malicious_expression" %>
		<%= f.label :reason_malicious_expression, "Malicious Expression", class: "form-check-label" %>
	</div>
	<div class="form-check">
		<%= f.radio_button :reason, "inappropriate_content" %>
		<%= f.label :reason_inappropriate_content, "Inappropriate Content", class: "form-check-label" %>
	</div>
	<div class="form-check">
		<%= f.radio_button :reason, "misinformation" %>
		<%= f.label :reason_misinformation, "Misinformation", class: "form-check-label" %>
	</div>
	<div class="form-check">
		<%= f.radio_button :reason, "commercial_purposes" %>
		<%= f.label :reason_commercial_purposes, "Commercial Purposes", class: "form-check-label" %>
	</div>
	<div class="form-check">
		<%= f.radio_button :reason, "spam" %>
		<%= f.label :reason_spam, "Spam", class: "form-check-label" %>
	</div>
	<div class="form-check">
		<%= f.radio_button :reason, "other" %>
		<%= f.label :reason_other, "Other", class: "form-check-label" %>
	</div>

	<%= f.hidden_field :content_id, value: params[:content_id] %>
	<%= f.hidden_field :content_type, value: params[:content_type] %>

	<div class="text-center mt-3">
		<%= f.submit "Report", class: "btn btn-dark" %>
	</div>
<% end %>

app/views/reports/create_failure.js.erb
$(".error-message").text("Failed !");

app/views/reports/create_success.js.erb
<!--通報成功メッセージを表示-->
$('.success-message').text('Success !');

<!--モーダルウィンドウを閉じる-->
$('#report-modal').addClass('fade-out');
setTimeout(() => {
  $('#report-modal').hide().removeClass('fade-out');
}, 300);

app/views/reports/index.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-10 mt-3 mx-auto'>
			<div class="h4 text-center">
				Reports
			</div>

			<% if @reports.present? %>
				<table class="table">
					<thead>
						<tr>
							<th>Reporter</th>
							<th>Reported</th>
							<th>Reason</th>
							<th>Created At</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						<% @reports.each do |report| %>
							<tr>
								<td>
									<div class="ml-3">
										<%= report.reporter.nickname %>
									</div>
								</td>
								<td>
									<div class="ml-3">
										<%= report.reported.nickname %>
									</div>
								</td>
								<td>
									<div class="ml-3">
										<%= report.reason %>
									</div>
								</td>
								<td>
									<div class="ml-3">
										<%= report.created_at.strftime('%m/%d/%Y %H:%M') %>
									</div>
								</td>
								<td>
									<div class="ml-3">
										<% if report.content_type == "User" %>
											<%= link_to "Show User", user_path(report.content), class: "text-secondary" %>
										<% elsif report.content_type == "Review" %>
											<%= link_to "Show Review", game_review_path(report.content.game, report.content), class: "text-secondary" %>
										<% elsif report.content_type == "Comment" %>
											<%= link_to "Show Comment", game_review_path(report.content.review.game, report.content.review), class: "text-secondary" %>
										<% end %>
										<%= button_to 'Delete', report_path(report), method: :delete,
											data: { confirm: 'Are you sure you want to delete this report ?' }, class: "btn btn-dark mt-2" %>
									</div>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>

				<div class="d-flex justify-content-center">
					<p>
						<%= paginate @reports, theme: 'bootstrap-5' %>
					</p>
				</div>
			<% else %>
				<div class="text-center">
					Nothing
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/reports/new.html.erb
<div class="error-message text-center"></div>
<div class="container">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			 <div class="report-title text-center mb-3">
					<h3>Report Form</h3>
				</div>
			<div class="d-flex justify-content-center">
				<div class="text-left">
					<%= render "report_form", report: @report %>
				</div>
			</div>
		</div>
	</div>
</div>